name: seats-reservation-management

services:
  # ===================================================
  # 1. REDIS CACHE
  # ===================================================
  redis-cache:
    image: redis:7-alpine
    container_name: seats-redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - seats-reservation-network

  # ===================================================
  # 2. NEXT.JS
  # ===================================================
  web-app:
    container_name: seats-reservation-app
    image: seats-reservation-management:latest
    build:
      context: ${BUILD_CONTEXT:-.}
      dockerfile: ${DOCKERFILE_PATH:-Dockerfile}
      args:
          - BUILD_MODE=${BUILD_MODE:-production}
          - DATABASE_PROVIDER=${DATABASE_PROVIDER:-sqlite}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_PROVIDER=sqlite
      - AUTH_PROVIDER=custom
      - NEXT_PUBLIC_AUTH_PROVIDER=custom
      - DATABASE_URL=file:/app/prisma/data/dev.db
      - REDIS_URL=redis://redis-cache:6379
      - JWT_SECRET=linkz-assessment-senior-lead-secret-key-2026
      - TOTAL_SEATS=15
      - SHOULD_SEED=true
      # make docker console utf8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      redis-cache:
        condition: service_healthy
    networks:
      - seats-reservation-network

networks:
  seats-reservation-network:
    driver: bridge

