name: 🚢 Seats Reservation Platform CI/CD Pipeline

on:
  # manual trigger workflow
  workflow_dispatch:

# permissions for GitHub Actions READ/WRITE
permissions:
  contents: read
  packages: write

# enviroment
env:
  LANG: 'C.UTF-8'
  LC_ALL: 'C.UTF-8'
  
  # GCP region
  GCP_REGION: us-central1   # Always Free
  
  # Docker image
  ENV_JSON_DOCKER_IMAGE: |
    [
      {
          "name":     "seats-reservation-sqlite",
          "env_vars": {
              "DATABASE_PROVIDER":          "sqlite"
          }
      },
      {
          "name":     "seats-reservation-postgres",
          "env_vars": {
              "DATABASE_PROVIDER":          "postgres"
          }
      }
    ]
  
  # GCP deploy
  ENV_JSON_GCP_DEPLOY: |
    [
      {
          "name":     "seats-reservation-sqlite",
          "env_vars": {
              "DATABASE_PROVIDER":          "sqlite",
              "AUTH_PROVIDER":              "custom",
              "NEXT_PUBLIC_AUTH_PROVIDER":  "custom",
              "DATABASE_URL":               "file:/app/prisma/data/seats_reservation.db",
              "DIRECT_DATABASE_URL":        "file:/app/prisma/data/seats_reservation.db",
              "REDIS_URL":                  "redis://redis-cache:6379",
              "JWT_SECRET":                 "seats-reservation-management-secret-key-2026",
              "TOTAL_SEATS":                9,
              "SHOULD_SEED":                true
          }
      },
      {
          "name":     "seats-reservation-postgres",
          "env_vars": {
              "DATABASE_PROVIDER":          "postgres",
              "AUTH_PROVIDER":              "custom",
              "NEXT_PUBLIC_AUTH_PROVIDER":  "custom",
              "REDIS_URL":                  "redis://redis-cache:6379",
              "JWT_SECRET":                 "seats-reservation-management-secret-key-2026",
              "TOTAL_SEATS":                9,
              "SHOULD_SEED":                true
          }
      }
    ]
  
  # GKE deploy
  ENV_JSON_GKE_DEPLOY: |
    [
      {
          "name":     "seats-reservation-sqlite",
          "env_vars": {
              "K8S_DEPLOYMENT_NAMESPACE":   "gke-seats-reservation-sqlite",
              "K8S_DEPLOYMENT_NAME":        "seats-reservation-deployment",
              "K8S_DEPLOYMENT_SERVICE":     "seats-reservation-service-lb",
              "K8S_DEPLOYMENT":             "./sources/.k8s/k8s-gke-deployment-sqlite.yml"
          }
      },
      {
          "name":     "seats-reservation-postgres",
          "env_vars": {
              "K8S_DEPLOYMENT_NAMESPACE":   "gke-seats-reservation-postgres",
              "K8S_DEPLOYMENT_NAME":        "seats-reservation-deployment",
              "K8S_DEPLOYMENT_SERVICE":     "seats-reservation-service-lb",
              "K8S_DEPLOYMENT_SECRET":      "seats-reservation-secret",
              "K8S_DEPLOYMENT":             "./sources/.k8s/k8s-gke-deployment-postgres.yml"
          }
      }
    ]

jobs:
  # ==============================================================================
  # ⚙️ SETUP CONFIGURATION JOB (Giải pháp sửa lỗi truyền biến env)
  # ==============================================================================
  setup-env:
    name: ⚙️ Setup enviroments for child CI/CD workflow
    runs-on: ubuntu-latest
    outputs:
      env_docker_image: ${{ steps.config.outputs.env_docker_image }}
      env_gcp_deploy: ${{ steps.config.outputs.env_gcp_deploy }}
      env_gke_deploy: ${{ steps.config.outputs.env_gke_deploy }}
      env_gke_gcp_region: ${{ steps.config.outputs.env_gke_gcp_region }}
    steps:
      - id: config
        name: ⚙️ Export JSON Environment Variables
        run: |
          # docker image enviroment variables
          echo "env_docker_image<<EOF" >> $GITHUB_OUTPUT
          echo '${{ env.ENV_JSON_DOCKER_IMAGE }}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # gcp deploy enviroment variables
          echo "env_gcp_deploy<<EOF" >> $GITHUB_OUTPUT
          echo '${{ env.ENV_JSON_GCP_DEPLOY }}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # gke deploy enviroment variables
          echo "env_gke_deploy<<EOF" >> $GITHUB_OUTPUT
          echo '${{ env.ENV_JSON_GKE_DEPLOY }}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # gcp/gke region enviroment variables
          echo "env_gke_gcp_region<<EOF" >> $GITHUB_OUTPUT
          echo '${{ env.GCP_REGION }}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  # ===================================================
  # 📋 REGRESSION & AUTOMATION E2E TEST (CI) - POSTGRES
  # ===================================================
  phase-test:
    uses: ./.github/workflows/ci-cd-test.yml
  
  # ==============================================================================
  # 🏗️ COMPILE DOCKER IMAGE
  # ==============================================================================
  phase-docker-image:
    uses: ./.github/workflows/ci-cd-docker-image.yml
    needs: [ setup-env, phase-test ]                        # wait for enviroment and test running successfully
    secrets: inherit # bypass secrets to child workflow
    with:
      env_data: ${{ needs.setup-env.outputs.env_docker_image }}
  
  # ==============================================================================
  # 🌐 GCP DEPLOYMENT
  # ==============================================================================
  phase-gcp-deploy:
    uses: ./.github/workflows/ci-cd-gcp-deploy.yml
    needs: [ setup-env, phase-test, phase-docker-image ]    # wait for enviroment, test, docker image running successfully
    secrets: inherit # bypass secrets to child workflow
    # redefine permissions due to override more permission for job
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      env_data: ${{ needs.setup-env.outputs.env_gcp_deploy }}
      region: ${{ needs.setup-env.outputs.env_gke_gcp_region }}
  
  # ==============================================================================
  # 🌐 GKE DEPLOYMENT
  # ==============================================================================
  phase-gke-deploy:
    uses: ./.github/workflows/ci-cd-gke-deploy.yml
    needs: [ setup-env, phase-test ]    # wait for enviroment, test running successfully
    secrets: inherit # bypass secrets to child workflow
    # redefine permissions due to override more permission for job
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      env_data: ${{ needs.setup-env.outputs.env_gke_deploy }}
      region: ${{ needs.setup-env.outputs.env_gke_gcp_region }}

