name: ☁️ [ GCP Deployment ] Seats Reservation Platform CI/CD Pipeline

on:
  # auto trigger workflow
  # push:
  #   branches: [ "master" ] # active when merge code into master
  # pull_request:
  #   branches: [ "master" ]

  # manual trigger workflow
  workflow_dispatch:
    inputs:
      env_data:
        required: false         # not require, due to be triggered standalone
        type: string            # receive enviroment from parent workflow under JSON string
        default: |
          [
            {
                "name":     "seats-reservation-sqlite",
                "env_vars": {
                    "DATABASE_PROVIDER":          "sqlite",
                    "AUTH_PROVIDER":              "custom",
                    "NEXT_PUBLIC_AUTH_PROVIDER":  "custom",
                    "DATABASE_URL=file":          "./seats_reservation.db",
                    "DIRECT_DATABASE_URL":        "file:./seats_reservation.db",
                    "REDIS_URL":                  "redis://redis-cache:6379",
                    "JWT_SECRET":                 "seats-reservation-management-secret-key-2026",
                    "TOTAL_SEATS":                9,
                    "SHOULD_SEED":                true
                }
            },
            {
                "name":     "seats-reservation-postgres",
                "env_vars": {
                    "DATABASE_PROVIDER":          "postgres",
                    "AUTH_PROVIDER":              "custom",
                    "NEXT_PUBLIC_AUTH_PROVIDER":  "custom",
                    "DATABASE_URL=file":          "postgresql://postgres:postgres_secret_pass@postgres-db:5432/seats_reservation?schema=public&pgbouncer=true",
                    "DIRECT_DATABASE_URL":        "postgresql://postgres:postgres_secret_pass@postgres-db:5432/seats_reservation?schema=public",
                    "REDIS_URL":                  "redis://redis-cache:6379",
                    "JWT_SECRET":                 "seats-reservation-management-secret-key-2026",
                    "TOTAL_SEATS":                9,
                    "SHOULD_SEED":                true
                }
            }
          ]
      region:
        required: false         # not require, due to be triggered standalone
        type: string            # receive enviroment from parent workflow under JSON string
        default: us-central1    # Always Free

# permissions for GitHub Actions READ/WRITE
permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  # ==============================================================================
  # 🌐 GCP DEPLOYMENT
  # ==============================================================================
  deploy-to-gcp:
    name: 🌐 Deploy to Google Cloud
    runs-on: ubuntu-latest
    # needs: build-and-push-to-docker-hub      # not require test running, due to be triggered standalone
    
    strategy:
      fail-fast: false
      matrix:
        # run parallel threads for services
        service: ${{ fromJson(inputs.env_data) }}

    steps:
    # Login to Google Cloud by OIDC
    - name: 🔑 Authenticate to Google Cloud via OIDC
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        create_credentials_file: false
    
    # Temporary Step: Convert deploy enviroment variables
    - name: 🔍 Format Environment Variables
      id: convert-deploy-env-vars
      run: |
        # Convert new line to comma (,)
        ENV_COMMA=$(echo '${{ matrix.service.env_vars }}' | jq -r 'to_entries | map("\(.key)=\(.value)") | join(",")')
        echo "converted_env_vars=$ENV_COMMA" >> $GITHUB_OUTPUT

    # Deploy to Google Cloud Run by pulling image from Docker Hub
    - name: 🚀 Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ matrix.service.name }}
        region: ${{ env.GCP_REGION }}
        # Point to Public Docker Hub, no need to use Google Artifact Registry API due to be charged
        image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:latest
        
        # ⚠️ Parameter to force system running in Free Tier Forever
        flags: |
          --allow-unauthenticated
          --min-instances=0
          --max-instances=1
          --memory=512Mi
          --cpu=1
          --set-env-vars="${{ steps.convert-deploy-env-vars.outputs.converted_env_vars }}" # apply enviroment for docker image

