name: ⚠️ [ GitHub Security ] Export All GitHub Secrets CI/CD Pipeline

on:
  # manual trigger workflow
  workflow_dispatch:
  

# enviroment
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  LANG: 'C.UTF-8'
  LC_ALL: 'C.UTF-8'

jobs:
  # ==============================================================================
  # ⚡ Dump GitHub Secrets
  # ==============================================================================
  export:
    name: ⚡ Dump GitHub Secrets
    runs-on: ubuntu-latest
    steps:
      # Check whether allow for running workflow
      - name: 🔐 Gatekeeper - Validate Administrative Access
        env:
          ALLOW_EXPORT_SECRETS: ${{ secrets.ALLOW_EXPORT_SECRETS }}
        if: ${{ env.ALLOW_EXPORT_SECRETS != 'true' }}
        run: |
          echo "❌ Deployment is administratively DISABLED via GitHub Secrets (secrets.ALLOW_EXPORT_SECRETS is not true)."
          echo "Terminating pipeline execution immediately to protect production infrastructure."
          exit 1 # Require Admin Rights
      
      # Check whether manager token permissions
      - name: 🛡️ Gatekeeper - Validate Manager Token Access
        if: success()                 # if previous step is successful
        env:
          # Use secret PAT to grant permission to update secrets instead of using default GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.PAT_SECRETS_MANAGER }}
        run: |
          echo "🛡️ Checking permissions to update..."
          if ! gh auth status > /dev/null 2>&1; then
            echo "❌ CRITICAL ERROR: Token 'PAT_SECRETS_MANAGER' is INVALID / EXPIRED / NOT EXISTED."
            echo "- Please check the GitHub Settings or contact repository administrators."
            exit 1
          fi
          echo "✅ Authenticated! Permissions had been grant!"
      
      # Dump secrets
      - name: 💾 Dump and Encode Secrets
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          echo "Whole GitHub Secrets (base64):"
          echo "$SECRETS_CONTEXT" | jq 'del(.github_token, .PAT_SECRETS_MANAGER)' | base64 -w 0
          echo ""

