name: ⚡ Generate and Export GCP/GKE Links to README

on:
  # manual trigger workflow
  workflow_dispatch:
    inputs:
      env_data:
        description: "🔧 Public URL(s)"
        required: false   # not require, due to be triggered standalone
        type: string      # receive enviroment from parent workflow under JSON string
        default: |
          [
            {
                "name":           "gcp-seats-reservation-sqlite",
                "published_url":  "",
                "encoded":        "false"
            },
            {
                "name":           "gcp-seats-reservation-postgres",
                "published_url":  "",
                "encoded":        "false"
            },
            {
                "name":           "gke-seats-reservation-sqlite",
                "published_url":  "",
                "encoded":        "false"
            },
            {
                "name":           "gke-seats-reservation-postgres",
                "published_url":  "",
                "encoded":        "false"
            }
          ]
  
  # allow other workflow call into (inputs same as workflow_dispatch but required)
  workflow_call:
    inputs:
      env_data:
        description: "🔧 Public URL(s)"
        required: true    # not require, due to be triggered standalone
        type: string      # receive enviroment from parent workflow under JSON string

# permissions for GitHub Actions READ/WRITE
permissions:
  contents: write
  packages: write

# enviroment
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  LANG: 'C.UTF-8'
  LC_ALL: 'C.UTF-8'

jobs:
  # ==============================================================================
  # 🏃 Publish URL to project README.md
  # ==============================================================================
  preparation-to-publish-url-readme:
    name: 🔍 Validate and Save the Published Service Information
    runs-on: ubuntu-latest
    
    # load services configuraion
    strategy:
      fail-fast: false
      matrix:
        # run parallel threads for services
        service: ${{ fromJson(inputs.env_data) }}

    steps:
      # Check whether allow for running workflow
      - name: 🛡️ Gatekeeper - Validate Administrative Access
        env:
          ALLOW_PUBLISH_README: ${{ secrets.ALLOW_PUBLISH_README }}
        if: ${{ env.ALLOW_PUBLISH_README != 'true' }}
        run: |
          echo "❌ Deployment is administratively DISABLED via GitHub Secrets (secrets.ALLOW_PUBLISH_README is not true)."
          echo "Terminating pipeline execution immediately to protect production infrastructure."
          exit 1 # Require Admin Rights
      
      # 1. Check whether allow for running workflow
      - name: 🛡️ Gatekeeper - Validate Published Service
        if: success()                 # if previous step is successful
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] || [ -z "${{ matrix.service.published_url }}" ]; then
            echo "❌ Ignore: ${{ matrix.service.name }} has invalid published URL."
            exit 1
          fi
      
      # 2. Save service published information to an temporary artifact for next step
      - name: 💾 Save Service URL to Temp File
        if: success()                 # if previous step is successful
        run: |
          # create JSON file contains the published information
          published_url=${{ matrix.service.published_url }}
          if [ "${{ matrix.service.encoded }}" = "true" ]; then
            published_url=$(echo "$published_url" | base64 --decode)
          fi
          echo '{"name": "${{ matrix.service.name }}", "published_url": "$published_url"}' > "published-${{ matrix.service.name }}.json"
      
      # 2.1. Upload published service JSON to an temporary artifact
      - name: 📦 Upload Published Service Information Artifact
        if: success()                 # if previous step is successful
        uses: actions/upload-artifact@v4
        with:
          name: published-service-${{ matrix.service.name }}
          path: "published-${{ matrix.service.name }}.json"
  
  # ==============================================================================
  # 🏃 Publish URL to project README.md
  # ==============================================================================
  publish-url-readme:
    name: 🏃 Publish URL to project README.md
    runs-on: ubuntu-latest
    needs: [ preparation-to-publish-url-readme ]
    if: success()                 # if previous job is successful
    
    steps:
      # 1. Check out source to publish README.md
      - name: ⬇️ Checkout Source Code
        uses: actions/checkout@v4

      # 2. Download Published Service Information Artifact from previous job to combine
      - name: 📥 Download All Service Artifacts
        if: success()                 # if previous step is successful
        uses: actions/download-artifact@v4
        with:
          # Use pattern (*) to download all artifacts with prefix `published-service-` to same folder
          pattern: published-service-*
          path: temp-published-urls
          merge-multiple: true # Merge all files `.json` to `temp-published-urls` folder
      
      # 3. Export the GCP public URL to README
      - name: 🔗 Generate and Export GCP Links to README
        if: success()                 # if previous step is successful
        run: |
          # 1. Check if not found any `.json` file from artifact
          if [ ! -d "temp-published-urls" ] || [ -z "$(ls -A temp-published-urls/published-*.json 2>/dev/null)" ]; then
            echo "⚠️ Not found any published service information JSON file."
            exit 1
          fi
          
          # 2. Use jq to collect all JSON files to one JSON Object (-s)
          # Ex: [{"name":"service-A","published_url":"url-A"},{"name":"service-B","published_url":"url-B"}]
          JSON_ARRAY=$(jq -s -c '.' temp-published-urls/published-*.json)
          
          echo "🏃 Published Services Information from Artifacts:"
          echo "$JSON_ARRAY"
          echo "----------------------------------------"
          
          # 3. Use jq to extract information (text) and loop
          # Line: tên_service|url_service
          echo "$JSON_ARRAY" | jq -r '.[] | "\(.name)|\(.published_url)"' | while os_line_read= read -r line; do
          
            # 3.1. Define your deployment variables
            SERVICE_NAME=$(echo "$line" | cut -d'|' -f1)
            PUBLIC_URL=$(echo "$line" | cut -d'|' -f2)
            TIME_STAMP="*(Last updated: $(date -u))*"
            
            # 2. Create the Markdown to update README
            PLACEHOLDER_START="<!-- START-${SERVICE_NAME} -->"
            PLACEHOLDER_END="<!-- END-${SERVICE_NAME} -->"
            LINK_MARKDOWN="[$PUBLIC_URL]($PUBLIC_URL)"
            REPLACEMENT_MARKDOWN="${LINK_MARKDOWN}<br> ${TIME_STAMP}"
            
            # 3. Build README
            update_readme_file() {
              local file_path="$1"
              if [ ! -f "$file_path" ]; then
                echo "⚠️ Ignore: Not found $file_path"
                return
              fi
              
              # 🚀 Use sed:
              # - Find START and END tags on same line, 
              # - Clear everything inside tags and replace $LINK_MARKDOWN into.
              sed -i ":a;N;\$!ba;s|${PLACEHOLDER_START}.*${PLACEHOLDER_END}|${PLACEHOLDER_START} ${REPLACEMENT_MARKDOWN} ${PLACEHOLDER_END}|g" "$file_path"
              echo "✔️ Updated $file_path successfully"
            }
            
            update_readme_file "$GITHUB_WORKSPACE/README.md"
            update_readme_file "$GITHUB_WORKSPACE/sources/README.md"
          
          done
          echo "✅ Done 👷"
      
      # # debugging
      # - name: 📄 Debug - Show updated README content
      #   if: success()                 # if previous step is successful
      #   run: |
      #     echo "===================================================="
      #     echo "🔍 [ PROJECT ] README.MD:"
      #     echo "===================================================="
      #     cat "$GITHUB_WORKSPACE/README.md"
      #     
      #     echo ""
      #     echo "===================================================="
      #     echo "🔍 [ SOURCES ] README.MD:"
      #     echo "===================================================="
      #     cat "$GITHUB_WORKSPACE/sources/README.md"
      #     echo "===================================================="
      
      # 4. Commit/Push modified README
      - name: 🚀 Auto Commit and Push README changes
        if: success()                 # if previous step is successful
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Docs: Automated update of published links for README.md [skip ci]"
          file_pattern: "README.md sources/README.md"
      
      # Clean up temporary artifact
      - name: 🧹 Clean up Temp Artifacts from GitHub Storage
        if: always()    # Always run to clean up
        uses: geekyeggo/delete-artifact@v5
        with:
          # Use pattern (*) to delete all artifacts with prefix `published-service-`
          name: published-service-*

