name: ℹ️ [ GitHub CI/CD ] Update Latest Workflows Status

on:
  workflow_run:
    # workflow names
    workflows: [
      "🚀 [ TEST ] Seats Reservation Platform CI/CD Pipeline",                         # E2E-Test workflow
      "📈 [ TEST ] Concurrency Stress Testing Loop (Pure k6 Load Injector)",           # K6-Test workflow
      "🐳 [ DOCKER IMAGE ] Seats Reservation Platform CI/CD Pipeline",                 # DockerHub workflow
      "☁️ [ GCP Deployment ] Seats Reservation Platform CI/CD Pipeline",               # GCP workflow
      "☁️ [ GKE Deployment ] Seats Reservation Platform CI/CD Pipeline",               # GKE workflow
      "🚢 Seats Reservation Platform CI/CD Pipeline",                                  # Main workflow
    ]
    types: [ completed ]
  # manual trigger workflow
  workflow_dispatch:

# permissions for GitHub Actions READ/WRITE
permissions:
  contents: read
  packages: write

# enviroment
env:
  LANG: 'C.UTF-8'
  LC_ALL: 'C.UTF-8'

# jobs
jobs:
  rename-run:
    name: 🏃 Update Latest Workflows Status
    runs-on: ubuntu-latest
    steps:
      # check-out source to read workflows list from .github/workflows folder
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # update workflows latest status
      - name: ⚙️ Update Workflow Run Name via GitHub API
        if: success()                 # if previous step is successful
        run: |
          REPO="${{ github.repository }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          # -------------------------------------------------------------
          # Extract workflows list by SED/AWK
          # -------------------------------------------------------------
          LOCAL_WF_PATH=".github/workflows/$(echo "${{ github.workflow }}" | sed 's/ /-/g').yml"
          if [ ! -f "$LOCAL_WF_PATH" ]; then
             CLEAN_PATH=$(echo "${{ github.workflow_ref }}" | cut -d'@' -f1)
             LOCAL_WF_PATH=".github/workflows/$(basename "$CLEAN_PATH")"
          fi
          echo "- 👷 Request Workflows to update from $LOCAL_WF_PATH"
          if [ ! -f "$LOCAL_WF_PATH" ]; then
             echo "-> ❌ Not found the workflows list from: $LOCAL_WF_PATH"
             exit 1
          fi
          
          echo "- 👷 Extract the workflows list to update..."
          RAW_LIST=$(yq '.on.workflow_run.workflows[]' "$LOCAL_WF_PATH")
          if [ -z "$RAW_LIST" ] || [ "$RAW_LIST" = "null" ]; then
             echo "-> ❌ Could not extract 'workflows:'. Please re-check the $LOCAL_WF_PATH file structure."
             exit 1
          fi
          IFS=$'\n' read -rd '' -a WORKFLOW_LIST <<< "$RAW_LIST"
          echo "-> ❌ Workflows list to update: ${WORKFLOW_LIST[*]}"
          
          # to update workflow title via API
          update_title() {
            local r_id="$1"
            local conclusion="$2"
            local msg="$3"
            
            if [ -z "$r_id" ] || [ "$r_id" = "null" ]; then return; fi
            
            local emoji="⚠️"
            if [ "$conclusion" = "success" ]; then emoji="✅"; fi
            if [ "$conclusion" = "failure" ]; then emoji="❌"; fi
            
            echo "---> 🔧 Update Run ID $r_id [ $emoji $conclusion ]"
            curl -s -X PATCH \
              -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://github.com" \
              -d "{\"run_name\":\"[$emoji $conclusion] Commit: $msg\"}"
          }
          
          # if automation trigger
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            CURRENT_WF="${{ github.event.workflow_run.name }}"
            echo "- 👷 Found workflow '$CURRENT_WF' has been done."
            
            RUN_ID="${{ github.event.workflow_run.id }}"
            CONCLUSION="${{ github.event.workflow_run.conclusion }}"
            COMMIT_MSG="${{ github.event.workflow_run.head_commit.message }}"
            
            update_title "$RUN_ID" "$CONCLUSION" "$COMMIT_MSG"
            
            # manuall trigger
          else
            echo "- 👷 Manual trigger. Scan running history..."
            RUN_DATA=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://github.com")
            # loop via workflows to update
            IFS=$'\n'
            for TARGET_WF in $RAW_LIST; do
              unset IFS
              TARGET_WF=$(echo "$TARGET_WF" | xargs)
              echo "-> 👷 Finding the latest running time: '$TARGET_WF'..."
              
              RUN_ID=$(echo "$RUN_DATA" | jq -r --arg name "$TARGET_WF" '.workflow_runs | map(select(.name == $name)) | .[0].id')
              CONCLUSION=$(echo "$RUN_DATA" | jq -r --arg name "$TARGET_WF" '.workflow_runs | map(select(.name == $name)) | .[0].conclusion')
              COMMIT_MSG=$(echo "$RUN_DATA" | jq -r --arg name "$TARGET_WF" '.workflow_runs | map(select(.name == $name)) | .[0].head_commit.message')
              
              # update workflow status
              if [ "$RUN_ID" != "null" ] && [ ! -z "$RUN_ID" ]; then
                update_title "$RUN_ID" "$CONCLUSION" "$COMMIT_MSG"
              else
                echo "---> ⚠️ Not found any running time of workflow '$TARGET_WF'."
              fi
            done
          fi
          
          echo "✔️ DONE 👷"

