name: 🚢 Seats Reservation Platform CI/CD Pipeline

on:
  # manual trigger workflow
  workflow_dispatch:

# permissions for GitHub Actions READ/WRITE
permissions:
  contents: read
  packages: write

# enviroment
env:
  LANG: 'C.UTF-8'
  LC_ALL: 'C.UTF-8'
  
  # GCP region
  GCP_REGION: us-central1   # Always Free
  
  # Docker image
  ENV_JSON_DOCKER_IMAGE: |
    [
      {
          "name":     "seats-reservation-sqlite",
          "env_vars": {
              "DATABASE_PROVIDER":          "sqlite"
          }
      },
      {
          "name":     "seats-reservation-postgres",
          "env_vars": {
              "DATABASE_PROVIDER":          "postgres"
          }
      }
    ]
  
  # GCP deploy
  ENV_JSON_GCP_DEPLOY: |
    [
      {
          "name":     "seats-reservation-sqlite",
          "env_vars": {
              "DATABASE_PROVIDER":          "sqlite",
              "AUTH_PROVIDER":              "custom",
              "NEXT_PUBLIC_AUTH_PROVIDER":  "custom",
              "DATABASE_URL":               "file:/app/data/seats_reservation.db",
              "DIRECT_DATABASE_URL":        "file:/app/data/seats_reservation.db",
              "REDIS_URL":                  "redis://redis-cache:6379",
              "JWT_SECRET":                 "seats-reservation-management-secret-key-2026",
              "TOTAL_SEATS":                9,
              "SHOULD_SEED":                true
          },
          "gcp_container_port":             3000
      },
      {
          "name":     "seats-reservation-postgres",
          "env_vars": {
              "DATABASE_PROVIDER":          "postgres",
              "AUTH_PROVIDER":              "custom",
              "NEXT_PUBLIC_AUTH_PROVIDER":  "custom",
              "DATABASE_URL":               "postgresql://postgres:postgres_secret_pass@postgres-db:5432/seats_reservation?schema=public&pgbouncer=true",
              "DIRECT_DATABASE_URL":        "postgresql://postgres:postgres_secret_pass@postgres-db:5432/seats_reservation?schema=public",
              "REDIS_URL":                  "redis://redis-cache:6379",
              "JWT_SECRET":                 "seats-reservation-management-secret-key-2026",
              "TOTAL_SEATS":                9,
              "SHOULD_SEED":                true
          },
          "gcp_container_port":             4000
      }
    ]

jobs:
  # ==============================================================================
  # ⚙️ SETUP CONFIGURATION JOB (Giải pháp sửa lỗi truyền biến env)
  # ==============================================================================
  setup-env:
    name: ⚙️ Setup enviroments for child CI/CD workflow
    runs-on: ubuntu-latest
    outputs:
      env_docker_image: ${{ steps.config.outputs.env_docker_image }}
      env_gcp_deploy: ${{ steps.config.outputs.env_gcp_deploy }}
    steps:
      - id: config
        name: ⚙️ Export JSON Environment Variables
        run: |
          # docker image enviroment variables
          echo "env_docker_image<<EOF" >> $GITHUB_OUTPUT
          echo '${{ env.ENV_JSON_DOCKER_IMAGE }}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # gcp deploy enviroment variables
          echo "env_gcp_deploy<<EOF" >> $GITHUB_OUTPUT
          echo '${{ env.ENV_JSON_GCP_DEPLOY }}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  # ===================================================
  # 📋 REGRESSION & AUTOMATION E2E TEST (CI) - POSTGRES
  # ===================================================
  phase-test:
    uses: ./.github/workflows/ci-cd-test.yml
  
  # ==============================================================================
  # 🏗️ COMPILE DOCKER IMAGE
  # ==============================================================================
  phase-docker-image:
    uses: ./.github/workflows/ci-cd-docker-image.yml
    needs: [ setup-env, phase-test ]                        # wait for enviroment and test running successfully
    secrets: inherit # bypass secrets to child workflow
    with:
      env_data: ${{ needs.setup-env.outputs.env_docker_image }}
  
  # ==============================================================================
  # 🌐 GCP DEPLOYMENT
  # ==============================================================================
  phase-gcp-deploy:
    uses: ./.github/workflows/ci-cd-gcp-deploy.yml
    needs: [ setup-env, phase-test, phase-docker-image ]    # wait for enviroment, test, docker image running successfully
    secrets: inherit # bypass secrets to child workflow
    # redefine permissions due to override more permission for job
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      env_data: ${{ needs.setup-env.outputs.env_gcp_deploy }}

